"""Initial migration

Revision ID: 308fd4c7635c
Revises: 
Create Date: 2025-02-04 16:24:57.207726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308fd4c7635c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('player_id'),
    sa.UniqueConstraint('name', name=op.f('uq_player_name'))
    )
    op.create_table('tournament',
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('format_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('tournament_id'),
    sa.UniqueConstraint('name', name=op.f('uq_tournament_name'))
    )
    op.create_table('tournament_playerlist',
    sa.Column('playerlist_id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('playerlist_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('tournament_playerlist')
    op.drop_table('tournament')
    op.drop_table('player')
    # ### end Alembic commands ###
