"""V0.12

Revision ID: 6f95e0d08891
Revises: eeb2e8397d79
Create Date: 2025-02-07 16:50:09.295114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f95e0d08891'
down_revision = 'eeb2e8397d79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rounds',
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.tournament_id'], name=op.f('fk_rounds_tournament_id_tournaments')),
    sa.PrimaryKeyConstraint('round_id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('round_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_matches_round_id_rounds'), 'rounds', ['round_id'], ['round_id'])

    with op.batch_alter_table('tournament_playerlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_playerlist', schema=None) as batch_op:
        batch_op.drop_column('group_id')

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_matches_round_id_rounds'), type_='foreignkey')
        batch_op.drop_column('round_id')

    op.drop_table('rounds')
    # ### end Alembic commands ###
