"""Add group number to Group model

Revision ID: 7da0f52133bc
Revises: eba635e05c45
Create Date: 2025-02-17 12:39:12.021640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7da0f52133bc'
down_revision = 'eba635e05c45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_number', sa.Integer(), nullable=False, server_default = '1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('group_number')

    # ### end Alembic commands ###
