"""V0.1

Revision ID: 86ff6af42861
Revises: 308fd4c7635c
Create Date: 2025-02-06 10:28:05.161162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ff6af42861'
down_revision = '308fd4c7635c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('player_id'),
    sa.UniqueConstraint('name', name=op.f('uq_players_name'))
    )
    op.create_table('tournament_formats',
    sa.Column('format_id', sa.Integer(), nullable=False),
    sa.Column('format_name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('format_id'),
    sa.UniqueConstraint('format_name', name=op.f('uq_tournament_formats_format_name'))
    )
    op.create_table('tournaments',
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('format_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['format_id'], ['tournament_formats.format_id'], name=op.f('fk_tournaments_format_id_tournament_formats')),
    sa.PrimaryKeyConstraint('tournament_id'),
    sa.UniqueConstraint('name', name=op.f('uq_tournaments_name'))
    )
    op.create_table('matches',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('player1_id', sa.Integer(), nullable=True),
    sa.Column('player2_id', sa.Integer(), nullable=True),
    sa.Column('score_player1', sa.Integer(), nullable=True),
    sa.Column('score_player2', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player1_id'], ['players.player_id'], name=op.f('fk_matches_player1_id_players')),
    sa.ForeignKeyConstraint(['player2_id'], ['players.player_id'], name=op.f('fk_matches_player2_id_players')),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.tournament_id'], name=op.f('fk_matches_tournament_id_tournaments')),
    sa.ForeignKeyConstraint(['winner_id'], ['players.player_id'], name=op.f('fk_matches_winner_id_players')),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.drop_table('player')
    op.drop_table('tournament')
    with op.batch_alter_table('tournament_playerlist', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_tournament_playerlist_tournament_id_tournaments'), 'tournaments', ['tournament_id'], ['tournament_id'])
        batch_op.create_foreign_key(batch_op.f('fk_tournament_playerlist_player_id_players'), 'players', ['player_id'], ['player_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_playerlist', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tournament_playerlist_player_id_players'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tournament_playerlist_tournament_id_tournaments'), type_='foreignkey')

    op.create_table('tournament',
    sa.Column('tournament_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('format_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('tournament_id'),
    sa.UniqueConstraint('name', name='uq_tournament_name')
    )
    op.create_table('player',
    sa.Column('player_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('player_id'),
    sa.UniqueConstraint('name', name='uq_player_name')
    )
    op.drop_table('matches')
    op.drop_table('tournaments')
    op.drop_table('tournament_formats')
    op.drop_table('players')
    # ### end Alembic commands ###
