"""Add group and update models

Revision ID: eba635e05c45
Revises: 6f95e0d08891
Create Date: 2025-02-16 14:23:38.989553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eba635e05c45'
down_revision = '6f95e0d08891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('group_name', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.tournament_id'], name=op.f('fk_groups_tournament_id_tournaments')),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('group_players',
    sa.Column('group_player_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], name=op.f('fk_group_players_group_id_groups')),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], name=op.f('fk_group_players_player_id_players')),
    sa.PrimaryKeyConstraint('group_player_id')
    )
    op.drop_table('tournament_playerlist')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_matches_group_id_groups'), 'groups', ['group_id'], ['group_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_matches_group_id_groups'), type_='foreignkey')
        batch_op.drop_column('group_id')

    op.create_table('tournament_playerlist',
    sa.Column('playerlist_id', sa.INTEGER(), nullable=False),
    sa.Column('tournament_id', sa.INTEGER(), nullable=True),
    sa.Column('player_id', sa.INTEGER(), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], name='fk_tournament_playerlist_player_id_players'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.tournament_id'], name='fk_tournament_playerlist_tournament_id_tournaments'),
    sa.PrimaryKeyConstraint('playerlist_id')
    )
    op.drop_table('group_players')
    op.drop_table('groups')
    # ### end Alembic commands ###
